### ISSUE TITLE
Compatible hostings 

### ISSUE THREAD

**Issue by matteoraggi** [hugsbrugs/php-phantomjs-get-html#3]
Is there a compatible hostings list?
Because I suppose that the hosting companies don't know this php-phantomjs and to answer if php-phantomjs is compatible or not, they ask you to buy the plan and test it and it take long time and to risk some money too..

**Comment by hugsbrugs** [comment]
Hey !
Most shared hosting will not allow you to execute phantomjs since it's very CPU/memory consuming.
The best wy to go is to have a virtual (or dedicated) server with at least 2GB of RAM.
Otherwise you should play on local machine :-(
